version: '3'
services:

  mongodb:
    image: mongo:4.4.6-bionic
    volumes:
      - /data/mongodb/configdb:/data/configdb
      - /data/mongodb/db:/data/db
      - /data/backup/mongodb:/data/backup

  iaa:
    image: registry.diginfra.net/lwo/iaa:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "80:3000"
    environment:
      - CONFIG_FILE=/opt/config-production.json
    volumes:
      - /opt/config-production.json:/opt/config-production.json:ro